stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/dvc_training/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/dvc_training/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/test
      - artifacts/data_ingestion/train
      - artifacts/data_ingestion/valid

  model_preparation:
    cmd: python src/cnnClassifier/pipeline/dvc_training/stage_02_model_preparation.py
    deps:
      - src/cnnClassifier/pipeline/dvc_training/stage_02_model_preparation.py
      - config/config.yaml
    params:
      - CLASSES
      - IMAGE_SIZE
    outs:
      - artifacts/prepare_base_model

  model_training:
    cmd: python src/cnnClassifier/pipeline/dvc_training/stage_03_model_training.py
    deps:
      - src/cnnClassifier/pipeline/dvc_training/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/test
      - artifacts/data_ingestion/train
      - artifacts/data_ingestion/valid
    params:
      - LEARNING_RATE
      - IMAGE_SIZE
      - AUGMENTATION
      - BATCH_SIZE
      - EPOCHS
    outs:
      - artifacts/training/model.pt

  model_evaluation:
    cmd: python src/cnnClassifier/pipeline/dvc_training/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/dvc_training/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/valid
      - artifacts/training/model.pt
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - artifacts/evaluation/scores.json:
          cache: false
