artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_URI: https://drive.google.com/file/d/1Mhpio2hV7UxUeFo19mtQfnctVEEvgT1L/view?usp=sharing
  zip_data_file: artifacts/data_ingestion/data.zip
  unzip_data_dir: artifacts/data_ingestion

model_preparation:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

model_training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  dataset_filename: face emotion data
